# ==== РАЗМЕРЫ ====
imgsz: 1280
batch: 4
workers: 0
rect: true
cache: true

# ==== ОПТИМИЗАЦИЯ ====
optimizer: AdamW
lr0: 0.00025
lrf: 0.001
weight_decay: 0.03
warmup_epochs: 2
cos_lr: true
amp: true

# ==== АУГМЕНТАЦИИ ====
mosaic: 0.0
mixup: 0.0
cutmix: 0.0
auto_augment: none
erasing: 0.0

hsv_h: 0.02
hsv_s: 0.5
hsv_v: 0.4

fliplr: 0.3
flipud: 0.0
degrees: 7.0
translate: 0.1
scale: 0.20
shear: 0.0
perspective: 0.0

# ==== ОБУЧЕНИЕ ====
epochs: 150
patience: 40
save_period: 20

# ==== ПРОЧЕЕ ====
pretrained: true
single_cls: false
simplify: true
